In [4]:
from __future__ import print_function
import torch

## 1.构造一个未初始化的5x3矩阵：

In [12]:
x = torch.empty(5, 3)

print(x)

tensor([[ 0.0454, -0.4670,  1.2718],
        [ 0.9950,  0.5242, -0.3427],
        [ 2.2475,  0.6522,  0.5677],
        [ 1.5001,  1.2440,  0.5095],
        [-0.9521, -0.7558, -0.9247]])


## 2.构造一个随机初始化的矩阵

In [13]:
x = torch.rand(5, 3)

print(x)

tensor([[0.3454, 0.6210, 0.2921],
        [0.7734, 0.0915, 0.6098],
        [0.2327, 0.4423, 0.6579],
        [0.4242, 0.9831, 0.6646],
        [0.8030, 0.2427, 0.3565]])


## 3.构造一个填充零且dtype为long的矩阵：

In [14]:
x = torch.zeros(5, 3, dtype=torch.long)

print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## 4.直接从数据构造张量

In [15]:
x = torch.tensor([5.5, 3])

print(x)

tensor([5.5000, 3.0000])


## 5.基于现有张量创建张量

In [16]:
x = x.new_ones(5, 3, dtype=torch.double)

print(x)

x = torch.randn_like(x, dtype=torch.float)

print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.5487, -0.9081,  0.9195],
        [-1.0215,  1.9570,  1.0485],
        [-1.5312, -0.0608, -0.2521],
        [-1.0825,  0.9212,  0.7229],
        [-2.4675, -1.4899,  0.5300]])


## 6.得到x的形状

In [17]:
print(x.size())

torch.Size([5, 3])


## 7.加法-语法1

In [18]:
y = torch.rand(5, 3)

print(x + y)

tensor([[ 1.8870, -0.1792,  1.8878],
        [-0.7512,  2.0458,  1.7743],
        [-1.3378,  0.6089, -0.1876],
        [-0.9710,  1.4503,  0.8310],
        [-2.4506, -1.3367,  1.2773]])


## 8.加法-语法2

In [20]:
print(torch.add(x, y))

tensor([[ 1.8870, -0.1792,  1.8878],
        [-0.7512,  2.0458,  1.7743],
        [-1.3378,  0.6089, -0.1876],
        [-0.9710,  1.4503,  0.8310],
        [-2.4506, -1.3367,  1.2773]])


## 9.加法:提供输出张量作为参数

In [19]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.8870, -0.1792,  1.8878],
        [-0.7512,  2.0458,  1.7743],
        [-1.3378,  0.6089, -0.1876],
        [-0.9710,  1.4503,  0.8310],
        [-2.4506, -1.3367,  1.2773]])


## 10.加法到位

In [21]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.8870, -0.1792,  1.8878],
        [-0.7512,  2.0458,  1.7743],
        [-1.3378,  0.6089, -0.1876],
        [-0.9710,  1.4503,  0.8310],
        [-2.4506, -1.3367,  1.2773]])


## 11.调整张量的大小

In [24]:
x = torch.randn(4, 4)

y = x.view(16)

z = x.view(-1, 8)

print(x.size(), y.size(),z.size())

print(x)

print(y)

print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[-0.9733,  1.0686, -0.8323,  1.8342],
        [-2.6640, -0.3427, -1.0638,  2.1748],
        [-0.4625, -1.5329,  0.7555, -0.1905],
        [-0.3171,  0.0836,  0.4390, -1.7839]])
tensor([-0.9733,  1.0686, -0.8323,  1.8342, -2.6640, -0.3427, -1.0638,  2.1748,
        -0.4625, -1.5329,  0.7555, -0.1905, -0.3171,  0.0836,  0.4390, -1.7839])
tensor([[-0.9733,  1.0686, -0.8323,  1.8342, -2.6640, -0.3427, -1.0638,  2.1748],
        [-0.4625, -1.5329,  0.7555, -0.1905, -0.3171,  0.0836,  0.4390, -1.7839]])


## 12.item()获取张量的数值

In [26]:
x = torch.randn(1)

print(x)

print(x.item())

tensor([-0.5211])
-0.5211282968521118


## 13.将torch的tensor转化为numpy的array

In [28]:
a = torch.ones(5)

print(a)

tensor([1., 1., 1., 1., 1.])


In [30]:
b = a.numpy()

print(b)

[1. 1. 1. 1. 1.]


In [32]:
a.add_(1)

print(a)

print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


## 14.将numpy的array转化为torch的tensor

In [34]:
import numpy as np

a = np.ones(5)

b = torch.from_numpy(a)

np.add(a, 1, out=a)

print(a)

print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 15.CUDA Tensors

In [35]:
if torch.cuda.is_available():
    
    device = torch.device("cuda")
    
    y = torch.ones_like(x, device=device)
    
    x = x.to(device)
    
    z = x + y
    print(z)
    
    print(z.to("cpu", torch.double))

tensor([0.4789], device='cuda:0')
tensor([0.4789], dtype=torch.float64)
